/*
Manage the flow of the Simon game
Keep track of the turn, and the list of buttons to press

Felipe de Araujo Barbosa
2024-04-24
*/

using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UI;

public class SimonController : MonoBehaviour
{
    [SerializeField] List<SimonButton> buttons;
    [SerializeField] List<int> sequence;
    [SerializeField] float delay;
    [SerializeField] int level;
    [SerializeField] int score;
    [SerializeField] bool playerTurn = false;

    [SerializeField] int counter = 0;
    [SerializeField] int numBottons;
    [SerializeField] GameObject buttonPrefab;
    [SerializeField] Transform buttonParent;
    public Text scoreText;

    public string apiData = @"
    {
        ""buttons"": [
            {
                ""id"": 0,
                ""r"": 1.0,
                ""g"": 0.0,
                ""b"": 0.5
            },
            {
                ""id"": 1,
                ""r"": 0.0,
                ""g"": 1.0,
                ""b"": 0.5
            },
            {
                ""id"": 2,
                ""r"": 0.0,
                ""g"": 0.5,
                ""b"": 1.0
            },
            {
                ""id"": 3,
                ""r"": 1.0,
                ""g"": 1.0,
                ""b"": 0.0
            }

        ]
    }
    ";

[SerializeField] ColorButtons allButtons;

    // Start is called before the first frame update
    void Start()
    {
        // Configure the buttons to be used in the game
        GetComponent<APIConection>().GetData();
    }

    // Configure the callback functions for the buttons
    public void PrepareButtons()
    {
        allButtons = JsonUtility.FromJson<ColorButtons>(apiData);

        foreach (ColorButton buttonData in allButtons.buttons)
        {
            GameObject newButton = Instantiate(buttonPrefab, buttonParent);
            newButton.GetComponent<Image>().color = new Color(buttonData.r, buttonData.g, buttonData.b);
            newButton.GetComponent<SimonButton>().Init(buttonData.id);
            newButton.GetComponent<Button>().onClick.AddListener(() => ButtonPressed(buttonData.id));
            buttons.Add(newButton.GetComponent<SimonButton>());
            
        }/*
        for (int i=0; i<numBottons; i++) {
            int index = i;
            GameObject newButton = Instantiate(buttonPrefab, buttonParent);
            newButton.GetComponent<Image>().color = Color.HSVToRGB((float)index/numBottons, 1, 1);
            newButton.GetComponent<SimonButton>().Init(index);
            buttons.Add(newButton.GetComponent<SimonButton>());
            buttons[i].gameObject.GetComponent<Button>().onClick.AddListener(() => ButtonPressed(index));
        }
        */
        // Start the game by adding the first button
        AddToSequence();
    }


public void UpdateScore(int level)
{
    score = level;
    scoreText.text = "Score: " + score.ToString();
    score++;
}
    // Main function to validate that the button pressed by the user 
    // corresponds with the sequence generated by the CPU
    public void ButtonPressed(int index) {
        if (playerTurn) {
            if (index == sequence[counter++]) {
                // Highlight the button selected by the player
                buttons[index].Highlight();
                if (counter == sequence.Count) {
                    // Finish the player turn to ensure no other actions are
                    // taken into account
                    playerTurn = false;
                    level++;
                    counter = 0;
                    AddToSequence();
                }
            } else {
                Debug.Log("Game Over!");
            }
        }
    }

    // Add another number to the sequence and display it
    void AddToSequence()
    {
        // Add a new button to the sequence
        sequence.Add(Random.Range(0, buttons.Count));
        StartCoroutine(PlaySequence());
    }

    // Display every button in the sequence so far
    IEnumerator PlaySequence()
    {
        // Add an initial delay before showing the sequence
        yield return new WaitForSeconds(delay);
        foreach (int index in sequence) {
            buttons[index].Highlight();
            yield return new WaitForSeconds(delay);
        }
        // Switch the turn over to the player
        playerTurn = true;
    }
}